plugins {
    id "architectury-plugin" version "3.4-SNAPSHOT"
    id "dev.architectury.loom" version "1.7.410" apply false
    id "io.github.pacifistmc.forgix" version "1.2.5"
}

architectury {
    minecraft = rootProject.minecraft_version
}

subprojects {
    apply plugin: "dev.architectury.loom"

    loom {
        // silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings "net.fabricmc:yarn:${rootProject.yarn_mappings}:v2"
        // mappings loom.officialMojangMappings()
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    archivesBaseName = rootProject.archives_base_name
    version = rootProject.mod_version
    group = rootProject.maven_group

    repositories {
        // Add repositories to retrieve artifacts from in here.
        // You should only use this when depending on other mods because
        // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
        // See https://docs.gradle.org/current/userguide/declaring_repositories.html
        // for more information about repositories.
        maven {
            url "https://maven.shedaniel.me/"
        }
        maven {
            url "https://maven.terraformersmc.com/releases/"
        }
    }

    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
        options.release = 17
    }

    java {
        withSourcesJar()
    }
}

forgix {
    // This is the common group of the mod which by default in Architectury Template it's defined as "maven_group" in your gradle.properties. If this property is not defined then by default it'll fetch the group from the maven_group property in your gradle.properties
    group = rootProject.maven_group
    // This is the name of the merged jar. If this property is not defined then by default it'll fetch the "archives_base_name" property with the "mod_version" property in your gradle.properties.
    mergedJarName = rootProject.archives_base_name + "-" + rootProject.mod_version + "-MERGED.jar"
    // This is the output directory of the merged jar from the root project. If this property is not defined then by default it's set to "Merged".
    outputDir = "build/libs"

    forge {
        // This is the name of the forge project. If this property is not defined then by default it'll set to "forge" since that's the name the Architectury Template uses.
        projectName = "forge"
        // This is the location of the forge jar from the forge project. If this property is not defined then by default it fetches the jar with the shortest name.
        jarLocation = "build/libs/" + rootProject.archives_base_name + "-" + rootProject.mod_version + "-FORGE.jar"

        mixin "originaddons.mixins.json" // This is in case if we didn't auto detect the forge mixins.
        mixin "originaddons-common.mixins.json"
    }

    fabric {
        // This is the name of the fabric project. If this property is not defined then by default it'll set to "fabric" since that's the name the Architectury Template uses.
        projectName = "fabric"
        // This is the location of the fabric jar from the fabric project. If this property is not defined then by default it fetches the jar with the shortest name.
        jarLocation = "build/libs/" + rootProject.archives_base_name + "-" + rootProject.mod_version + "-FABRIC.jar"
    }

    // This should be used to remove a duplicate package
    removeDuplicate "me.shedaniel.clothconfig"
}